/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=WorkerBindings worker/worker-configuration.d.ts` (hash: 61126b2ac64a525d310763d1f3be24f1)
interface __BaseEnv_WorkerBindings {
	CACHE: R2Bucket;
	DB: D1Database;
	VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	OWNER_EMAIL: string;
	GITHUB_TOKEN_EXPIRES_AT: string;
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "OWNER_EMAIL" | "GITHUB_TOKEN_EXPIRES_AT" | "GITHUB_TOKEN">> {}
}
